---
- name: Running memtier Benchmark
  hosts: client
  vars_files:
    - ../constants.yml

  tasks:
      - name: "MT: Exp {{ exp_id }}.{{ sub_exp }} (WT={{ worker_threads }} | CT={{ ct }} VC={{ vc }} | {{ repetition }}/3) {{ type }} @ {{ memtier_targets }} (-> {{ log_path }})"
        command: ./memtier_helper.sh --key-size {{ maximum_key_size }} --data-size {{ maximum_data_size }} --virtual-clients {{ vc }} --threads {{ ct }} --set-ratio {{ set_ratio }} --get-ratio {{ get_ratio }} --multiget-count {{ multiget_count }} --runtime {{ test_duration }} --log-path {{ log_path }} {{ memtier_targets }}
