---
- name: "Running Memtier"
  hosts: client
  vars_files:
    - ../templates/templates_v1.yml

  tasks:
    # - import_tasks: ../basic_blocks/create-logdir.yml

    - name: "Experiment {{ exp_id }}.{{ sub_exp }} ({{ worker_threads }} | {{ vc }}/{{ repetition }}) {{ type }} @ {{ memtier_targets }}"
      command: ./memtier_helper.sh --key-size {{ maximum_key_size }} --data-size {{ maximum_data_size }} --virtual-clients {{ vc }} -- threads {{ ct }} --set-ratio {{ set_ratio }} --get-ratio {{ get_ratio }} --multiget-count {{ multiget_count }} --runtime {{ test_duration }} --log-path {{ log_base }} --log-base {{ type }} {{ memtier_targets }}

    # - name: Fixing history log
    #   command: perl -p -i -e 's/\r/\n/g' {{ log_memtier_stderr }}

    # - import_tasks: ../basic_blocks/global-sleep.yml
