# -*- mode: ruby -*-
# vi: set ft=ruby :

$instances = 8
$memory = 1024
$cpus = 1

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.box_check_update = false
    #config.vm.synched_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
        libvirt.storage_pool_name = "user-vms"

        libvirt.cpus = $cpus
        libvirt.memory = $memory
        libvirt.cpu_mode = 'host-passthrough'

        libvirt.graphics_type = "spice"
        libvirt.video_type = 'qxl'

        libvirt.keymap = 'de'

        libvirt.disk_bus = 'virtio'
    end

    (1..$instances).each do |machine_id|
        config.vm.define vm_name = "asl%d" % machine_id do |asl|
            asl.vm.hostname = vm_name

            asl.vm.network "private_network", ip: "192.168.122.#{machine_id+100}"
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/provision-vm.yml"
        ansible.limit = "all"
        #ansible.groups = {
        #    "vm" => "syscon_vm"
        #}
    end
end
