# -*- mode: ruby -*-
# vi: set ft=ruby :

$memory = 1024
$cpus = 1

$mw_instances = 2
$tier_instances = 3
$cache_instances = 3
$test_instances = 1

$instances = $tier_instances + $mw_instances + $cache_instances

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.box_check_update = false

    # Don't use NFS at all
    config.nfs.functional = false
    config.nfs.verify_installed = false
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provider :libvirt do |libvirt|
        libvirt.default_prefix = "ASL"
        libvirt.storage_pool_name = 'user-vms'

        libvirt.cpus = $cpus
        libvirt.memory = $memory
        libvirt.cpu_mode = 'host-passthrough'

        libvirt.graphics_type = 'spice'
        libvirt.video_type = 'qxl'

        libvirt.keymap = 'de'

        libvirt.disk_bus = 'virtio'
    end

    # (1..$test_instances).each do |machine_id|
    #     config.vm.define vm_name = "Test%d" % machine_id do |asl|
    #         asl.vm.hostname = vm_name
    #         asl.vm.network :private_network,
    #             # :type => 'dhcp',
    #             :ip => "192.168.122.#{machine_id+200}"
    #     end
    # end

    (1..$tier_instances).each do |machine_id|
        config.vm.define vm_name = "Client%d" % machine_id do |asl|
            asl.vm.hostname = vm_name
            asl.vm.network :private_network,
                # :type => 'dhcp',
                :ip => "192.168.122.#{machine_id+100}"
        end
    end

    (1..$mw_instances).each do |machine_id|
        config.vm.define vm_name = "Middleware%d" % machine_id do |asl|
            asl.vm.hostname = vm_name
            asl.vm.network :private_network,
                # :type => 'dhcp',
                :ip => "192.168.122.#{machine_id+$tier_instances+100}"
        end
    end

    (1..$cache_instances).each do |machine_id|
        config.vm.define vm_name = "Server%d" % machine_id do |asl|
            asl.vm.hostname = vm_name
            asl.vm.network :private_network,
                # :type => 'dhcp',
                :ip => "192.168.122.#{machine_id+$tier_instances+$mw_instances+100}"
        end
    end

    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", privileged: false, inline: "cat ~/.ssh/me.pub >> ~/.ssh/authorized_keys && rm ~/.ssh/me.pub"

end
