---
- hosts: asl-cnc
  gather_facts: true

  tasks:
  - name: Installing client software (Ubuntu)
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - git
      - build-essential
      - autoconf
      - automake
      - libpcre3-dev
      - libevent-dev
      - pkg-config
      - zlib1g-dev
    become: true

  - name: Downloading memtier sources
    git:
      repo: "https://github.com/RedisLabs/memtier_benchmark"
      dest: ~/memtier_benchmark
      version: 1.2.12

  - name: Configuring memtier
    command: '{{ item }} chdir=~/memtier_benchmark'
    with_items:
      - autoreconf -ivf
      - ./configure

  - name: Building memtier
    command: make chdir=~/memtier_benchmark

  - name: Installing memtier
    command: make install chdir=/home/asl/memtier_benchmark
    become: true
