---
- hosts: server
  become: true

  tasks:
  - name: Installing required software (Ubuntu)
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - memcached
        - dstat
        - iperf
        - rsync

  - name: Make memcached listen on ANY interface
    replace:
        dest: /etc/memcached.conf
        regexp: '^-l 127.0.0.1'
        replace: '#-l 127.0.0.1'

  - name: Make memcached single threaded
    lineinfile:
        dest: /etc/memcached.conf
        line: '-t 1 # Run memcached single threaded'

  - name: "Starting memcached"
    systemd:
        name: memcached
        enabled: yes
        state: started
