---
- name: Provisioning Server Machines For Experiments
  hosts: server
  become: true

  tasks:
  - name: Installing System Software
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - memcached
        - dstat
        - iperf
        - rsync

  - name: Reconfigure memcached To Listen To Any Interface
    replace:
        dest: /etc/memcached.conf
        regexp: '^-l 127.0.0.1'
        replace: '#-l 127.0.0.1'

  - name: Reconfigure memcached For Single-Threaded Mode
    lineinfile:
        dest: /etc/memcached.conf
        line: '-t 1 # Run memcached single threaded'

  - name: Restarting Memcached
    systemd:
        name: memcached
        enabled: yes
        state: restarted
