---
- name: Provisioning Middleware Machines For Experiments
  hosts: middleware
  become: true

  tasks:
  - name: Installing System Software
    apt:
        name: "{{ packages }}"
        update_cache: yes
        state: present
    vars:
        packages:
        - openjdk-8-jdk-headless
        - dstat
        - iperf
        - rsync
