---
- name: Starting Middleware
  hosts: middleware
  vars_files:
      - ../constants.yml

  tasks:
    - name: "MW: Exp {{ exp_id }}.{{ sub_exp }} (WT={{ worker_threads }} | CT={{ ct }} VC={{ vc }} | {{ repetition }}/3) {{ type }} @ {{ memcached_server_list }} (-> {{ log_path }})"
      shell: "nohup ./middleware_helper.sh --jar-path {{ mw_jar_file }} --listen-ip {{ ip }} --listen-port {{ port }} --worker-threads {{ worker_threads }} --is-sharded {{ is_sharded }} --log-path {{ log_path }} {{ memcached_server_list }} </dev/null >/dev/null 2>&1 &"

    - import_tasks: ../basic_blocks/global-sleep.yml
