---
- name: Stopping Middleware
  hosts: middleware
  vars_files:
      - ../constants.yml

  tasks:
    - name: Getting Middleware's PID
      shell: "ps -ef | grep -v grep | grep -v bash | grep -w middleware-mickeyv.jar | awk '{print $2}'"
      register: middleware_pid

    - name: Getting helper script's PID
      shell: "ps -ef | grep -v grep | grep -w bash | grep -w middleware-mickeyv.jar | awk '{print $2}'"
      register: helper_pid

    - name: Stopping Middleware
      command: "kill {{ item }}"
      with_items: "{{ middleware_pid.stdout_lines }}"

    # The following two commands may be rather ugly and not very log-friendly
    - name: Waiting for helper script to finish
      wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
        connect_timeout: 1
        timeout: 10
      with_items: "{{ helper_pid.stdout_lines }}"
      ignore_errors: yes
      register: killed_processes

    - name: Killing Middleware
      command: "kill -9 {{ item }}"
      with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
