---
- name: Updating Middleware JAR
  hosts: middleware
  vars_files:
      - ../constants.yml

  tasks:
    - name: Pushing To Host
      synchronize:
        src: ../../../../middleware/dist/middleware-mickeyv.jar
        dest: "{{ mw_jar_path }}"
