---
- hosts: all
  vars_files:
      - ../constants.yml

  tasks:
    - name: Retrieving logs from machine
      ignore_errors: yes
      synchronize:
          mode: pull
          src: "{{ log_dir }}"
          dest: ~/

    - name: Deleting logs on machine
      ignore_errors: yes
      file:
          path: ~/logs
          state: absent

# - name: Sleeping 2 seconds
#   pause:
#       seconds: 2
