---
- name: Pulling logs From Machines
  hosts: all
  vars_files:
      - ../constants.yml

  tasks:
    - name: Copying logs From Remote
      ignore_errors: yes
      synchronize:
          mode: pull
          src: "{{ log_dir }}"
          dest: ~/

    - name: Deleting logs On Remote
      ignore_errors: yes
      file:
          path: ~/logs
          state: absent
