---
- name: Generate log directory
  file:
      path: "{{ log_base }}"
      state: directory

- name: "[ {{ exp_id }}/{{ sub_exp }} | {{ worker_threads }} | {{ vc }}/{{ repetition }}] {{ type }} - ({{ memtier_target }}:{{ memtier_target_port }}|{{ memtier_target2 }}:{{ memtier_target2_port }})"
  shell: |
      {{ dstat_cmd }} > {{ log_memtier_dstat }} &
      ping {{ memtier_target }} > {{ log_memtier_ping }} &
      ping {{ memtier_target2 }} > {{ log2_memtier_ping }} &
      {{ mt_cmd_log }} & {{ mt_cmd2_log }}

- name: Fixing history log
  command: perl -p -i -e 's/\r/\n/g' "{{ logs_to_fix }}"
  with_items:
      - "{{ log_memtier_stderr }}"
      - "{{ log2_memtier_stderr }}"
  loop_control:
      loop_var: logs_to_fix

- name: Sleeping 3 seconds
  pause:
      seconds: 3
